CREATE TABLE GAME (
	ID INT(11) NOT NULL PRIMARY KEY AUTO_INCREMENT,
	START_TIME DATETIME,
	FIRST_NAME VARCHAR(255),
	LAST_NAME VARCHAR(255),
	COMPANY_NAME VARCHAR(255),
	TITLE VARCHAR(255),
	EMAIL VARCHAR(255)
);

CREATE TABLE SHOT (
	ID INT(11) NOT NULL PRIMARY KEY AUTO_INCREMENT,
	GAME_ID INT(11),
	POINTS INT(11)
);

ALTER TABLE SHOT
	ADD KEY FK_SHOT_GAME_ID (GAME_ID);
	
ALTER TABLE SHOT
	ADD CONSTRAINT FK_SHOT_GAME_ID FOREIGN KEY (GAME_ID) REFERENCES GAME (ID) ON DELETE NO ACTION ON UPDATE NO ACTION;