CREATE TABLE HAE_REFERENCE(
ID INT(10) NOT NULL AUTO_INCREMENT PRIMARY KEY,
LABEL varchar(255), 
VALUE varchar(255),
CUSTOM varchar(255),
CATEGORY varchar(255),
DISPLAY_ORDER INT(10) DEFAULT 0,
DELETED TINYINT(1) DEFAULT 0
);