CREATE TABLE HAE_REFERENCE(
	ID INT(10),
	LABEL VARCHAR(255), 
	VALUE VARCHAR(255),
	CUSTOM VARCHAR(255),
	CATEGORY VARCHAR(255),
	DISPLAY_ORDER INT(10) DEFAULT 0,
	DELETED TINYINT(1) DEFAULT 0,
	PRIMARY KEY (ID) 
);